// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wock.Data;

#nullable disable

namespace Wock.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260507064902_EnforceSingleActiveWorkEntry")]
    partial class EnforceSingleActiveWorkEntry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("Wock.Models.BookingTarget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BookingSoftware")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("BookingTicketId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("IsActive");

                    b.ToTable("BookingTargets");
                });

            modelBuilder.Entity("Wock.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Wock.Models.InstalledPlugin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssemblyPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InstalledAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("LastLoadError")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastLoadStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("NotLoaded");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PluginId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsEnabled");

                    b.HasIndex("LastLoadStatus");

                    b.HasIndex("PluginId")
                        .IsUnique();

                    b.ToTable("InstalledPlugins");
                });

            modelBuilder.Entity("Wock.Models.WorkEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ActiveSlot")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("INTEGER")
                        .HasComputedColumnSql("CASE WHEN Status IN ('Running', 'Paused') THEN 1 ELSE NULL END");

                    b.Property<int?>("BookingTargetId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalTicketId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StoppedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalPausedSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActiveSlot")
                        .IsUnique()
                        .HasDatabaseName("IX_WorkEntries_OneActiveEntry")
                        .HasFilter("ActiveSlot IS NOT NULL");

                    b.HasIndex("BookingTargetId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ExternalTicketId");

                    b.HasIndex("StartedAt");

                    b.HasIndex("Status");

                    b.HasIndex("CustomerId", "StartedAt");

                    b.HasIndex("Status", "StartedAt");

                    b.ToTable("WorkEntries", t =>
                        {
                            t.HasCheckConstraint("CK_WorkEntries_TotalPausedSeconds_NonNegative", "TotalPausedSeconds >= 0");
                        });
                });

            modelBuilder.Entity("Wock.Models.WorkEntryPause", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PausedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResumedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkEntryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PausedAt");

                    b.HasIndex("WorkEntryId");

                    b.ToTable("WorkEntryPauses");
                });

            modelBuilder.Entity("Wock.Models.BookingTarget", b =>
                {
                    b.HasOne("Wock.Models.Customer", "Customer")
                        .WithMany("BookingTargets")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Wock.Models.WorkEntry", b =>
                {
                    b.HasOne("Wock.Models.BookingTarget", "BookingTarget")
                        .WithMany("WorkEntries")
                        .HasForeignKey("BookingTargetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Wock.Models.Customer", "Customer")
                        .WithMany("WorkEntries")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BookingTarget");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Wock.Models.WorkEntryPause", b =>
                {
                    b.HasOne("Wock.Models.WorkEntry", "WorkEntry")
                        .WithMany("Pauses")
                        .HasForeignKey("WorkEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkEntry");
                });

            modelBuilder.Entity("Wock.Models.BookingTarget", b =>
                {
                    b.Navigation("WorkEntries");
                });

            modelBuilder.Entity("Wock.Models.Customer", b =>
                {
                    b.Navigation("BookingTargets");

                    b.Navigation("WorkEntries");
                });

            modelBuilder.Entity("Wock.Models.WorkEntry", b =>
                {
                    b.Navigation("Pauses");
                });
#pragma warning restore 612, 618
        }
    }
}
