// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wock.Data;

#nullable disable

namespace Wock.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260513124420_AddProjectsBillingWorkflow")]
    partial class AddProjectsBillingWorkflow
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Wock.Features.Users.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Wock.Features.Users.Models.ApplicationUserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Role");

                    b.HasIndex("UserId", "Role")
                        .IsUnique();

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Wock.Models.ActivityCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("SortOrder");

                    b.ToTable("ActivityCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Beratung",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Entwicklung",
                            SortOrder = 20
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Design",
                            SortOrder = 30
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Projektmanagement",
                            SortOrder = 40
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "Support",
                            SortOrder = 50
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            Name = "Testing",
                            SortOrder = 60
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            Name = "Dokumentation",
                            SortOrder = 70
                        },
                        new
                        {
                            Id = 8,
                            IsActive = true,
                            Name = "Administration",
                            SortOrder = 80
                        },
                        new
                        {
                            Id = 9,
                            IsActive = true,
                            Name = "Vertrieb",
                            SortOrder = 90
                        },
                        new
                        {
                            Id = 10,
                            IsActive = true,
                            Name = "Meeting",
                            SortOrder = 100
                        },
                        new
                        {
                            Id = 11,
                            IsActive = true,
                            Name = "Sonstiges",
                            SortOrder = 110
                        });
                });

            modelBuilder.Entity("Wock.Models.BookingTarget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BookingSoftware")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("BookingTicketId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("OwnerUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("IsActive");

                    b.HasIndex("ModifiedByUserId");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("BookingTargets");
                });

            modelBuilder.Entity("Wock.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BillingAddress")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ContactName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("DefaultHourlyRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("OwnerUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("IsActive");

                    b.HasIndex("ModifiedByUserId");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Wock.Models.InstalledPlugin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssemblyPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("InstalledAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastLoadError")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("LastLoadStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("NotLoaded");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PluginId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("IsEnabled");

                    b.HasIndex("LastLoadStatus");

                    b.HasIndex("ModifiedByUserId");

                    b.HasIndex("PluginId")
                        .IsUnique();

                    b.ToTable("InstalledPlugins");
                });

            modelBuilder.Entity("Wock.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BillingModel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal?>("BudgetAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("BudgetHours")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<decimal?>("DefaultHourlyRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateOnly?>("EndsOn")
                        .HasColumnType("date");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OwnerUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly?>("StartsOn")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ModifiedByUserId");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("Status");

                    b.HasIndex("CustomerId", "Name");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Wock.Models.ProjectTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActivityCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("AssignedUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OwnerUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ActivityCategoryId");

                    b.HasIndex("AssignedUserId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ModifiedByUserId");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("Status");

                    b.HasIndex("ProjectId", "Title");

                    b.ToTable("ProjectTasks");
                });

            modelBuilder.Entity("Wock.Models.WorkEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActiveOwnerSlot")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasComputedColumnSql("CASE WHEN Status IN ('Running', 'Paused') THEN COALESCE(OwnerUserId, '') ELSE NULL END");

                    b.Property<int?>("ActivityCategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApprovedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BillingCategory")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("BookingTargetId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ExternalTicketId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("HourlyRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsBillable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OwnerUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int?>("ProjectTaskId")
                        .HasColumnType("int");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Draft");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("StoppedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalPausedSeconds")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActiveOwnerSlot")
                        .IsUnique()
                        .HasDatabaseName("IX_WorkEntries_OneActiveEntry")
                        .HasFilter("ActiveOwnerSlot IS NOT NULL");

                    b.HasIndex("ActivityCategoryId");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("BookingTargetId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ExternalTicketId");

                    b.HasIndex("ModifiedByUserId");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ProjectTaskId");

                    b.HasIndex("ReviewStatus");

                    b.HasIndex("StartedAt");

                    b.HasIndex("Status");

                    b.HasIndex("CustomerId", "StartedAt");

                    b.HasIndex("OwnerUserId", "ReviewStatus");

                    b.HasIndex("ProjectId", "StartedAt");

                    b.HasIndex("Status", "StartedAt");

                    b.ToTable("WorkEntries", t =>
                        {
                            t.HasCheckConstraint("CK_WorkEntries_TotalPausedSeconds_NonNegative", "TotalPausedSeconds >= 0");
                        });
                });

            modelBuilder.Entity("Wock.Models.WorkEntryPause", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("PausedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ResumedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkEntryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PausedAt");

                    b.HasIndex("WorkEntryId");

                    b.ToTable("WorkEntryPauses");
                });

            modelBuilder.Entity("Wock.Features.Users.Models.ApplicationUserRole", b =>
                {
                    b.HasOne("Wock.Features.Users.Models.ApplicationUser", "User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Wock.Models.BookingTarget", b =>
                {
                    b.HasOne("Wock.Features.Users.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.ClientNoAction);

                    b.HasOne("Wock.Models.Customer", "Customer")
                        .WithMany("BookingTargets")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wock.Features.Users.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ModifiedByUserId")
                        .OnDelete(DeleteBehavior.ClientNoAction);

                    b.HasOne("Wock.Features.Users.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.ClientNoAction);

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Wock.Models.Customer", b =>
                {
                    b.HasOne("Wock.Features.Users.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.ClientNoAction);

                    b.HasOne("Wock.Features.Users.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ModifiedByUserId")
                        .OnDelete(DeleteBehavior.ClientNoAction);

                    b.HasOne("Wock.Features.Users.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.ClientNoAction);
                });

            modelBuilder.Entity("Wock.Models.InstalledPlugin", b =>
                {
                    b.HasOne("Wock.Features.Users.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.ClientNoAction);

                    b.HasOne("Wock.Features.Users.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ModifiedByUserId")
                        .OnDelete(DeleteBehavior.ClientNoAction);
                });

            modelBuilder.Entity("Wock.Models.Project", b =>
                {
                    b.HasOne("Wock.Features.Users.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.ClientNoAction);

                    b.HasOne("Wock.Models.Customer", "Customer")
                        .WithMany("Projects")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wock.Features.Users.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ModifiedByUserId")
                        .OnDelete(DeleteBehavior.ClientNoAction);

                    b.HasOne("Wock.Features.Users.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.ClientNoAction);

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Wock.Models.ProjectTask", b =>
                {
                    b.HasOne("Wock.Models.ActivityCategory", "ActivityCategory")
                        .WithMany("ProjectTasks")
                        .HasForeignKey("ActivityCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Wock.Features.Users.Models.ApplicationUser", "AssignedUser")
                        .WithMany()
                        .HasForeignKey("AssignedUserId")
                        .OnDelete(DeleteBehavior.ClientNoAction);

                    b.HasOne("Wock.Features.Users.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.ClientNoAction);

                    b.HasOne("Wock.Features.Users.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ModifiedByUserId")
                        .OnDelete(DeleteBehavior.ClientNoAction);

                    b.HasOne("Wock.Features.Users.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.ClientNoAction);

                    b.HasOne("Wock.Models.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActivityCategory");

                    b.Navigation("AssignedUser");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Wock.Models.WorkEntry", b =>
                {
                    b.HasOne("Wock.Models.ActivityCategory", "ActivityCategory")
                        .WithMany("WorkEntries")
                        .HasForeignKey("ActivityCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Wock.Features.Users.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.ClientNoAction);

                    b.HasOne("Wock.Models.BookingTarget", "BookingTarget")
                        .WithMany("WorkEntries")
                        .HasForeignKey("BookingTargetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Wock.Features.Users.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.ClientNoAction);

                    b.HasOne("Wock.Models.Customer", "Customer")
                        .WithMany("WorkEntries")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wock.Features.Users.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ModifiedByUserId")
                        .OnDelete(DeleteBehavior.ClientNoAction);

                    b.HasOne("Wock.Features.Users.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.ClientNoAction);

                    b.HasOne("Wock.Models.Project", "Project")
                        .WithMany("WorkEntries")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Wock.Models.ProjectTask", "ProjectTask")
                        .WithMany("WorkEntries")
                        .HasForeignKey("ProjectTaskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ActivityCategory");

                    b.Navigation("BookingTarget");

                    b.Navigation("Customer");

                    b.Navigation("Project");

                    b.Navigation("ProjectTask");
                });

            modelBuilder.Entity("Wock.Models.WorkEntryPause", b =>
                {
                    b.HasOne("Wock.Models.WorkEntry", "WorkEntry")
                        .WithMany("Pauses")
                        .HasForeignKey("WorkEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkEntry");
                });

            modelBuilder.Entity("Wock.Features.Users.Models.ApplicationUser", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("Wock.Models.ActivityCategory", b =>
                {
                    b.Navigation("ProjectTasks");

                    b.Navigation("WorkEntries");
                });

            modelBuilder.Entity("Wock.Models.BookingTarget", b =>
                {
                    b.Navigation("WorkEntries");
                });

            modelBuilder.Entity("Wock.Models.Customer", b =>
                {
                    b.Navigation("BookingTargets");

                    b.Navigation("Projects");

                    b.Navigation("WorkEntries");
                });

            modelBuilder.Entity("Wock.Models.Project", b =>
                {
                    b.Navigation("Tasks");

                    b.Navigation("WorkEntries");
                });

            modelBuilder.Entity("Wock.Models.ProjectTask", b =>
                {
                    b.Navigation("WorkEntries");
                });

            modelBuilder.Entity("Wock.Models.WorkEntry", b =>
                {
                    b.Navigation("Pauses");
                });
#pragma warning restore 612, 618
        }
    }
}
